---
- name: Deploy vless-config-generator-api nginx upstream config
  ansible.builtin.template:
    src: upstream.conf.j2
    dest: "{{ nginx_custom_upstream_path }}/vless-config-generator-api.conf"
    mode: '0644'
  become: yes
  notify: Reload nginx
  tags:
    - vless-config-generator
    - vless-config-generator-nginx

- name: Deploy vless-config-generator nginx location config
  ansible.builtin.template:
    src: location.conf.j2
    dest: "{{ nginx_domain_custom_locations_path }}/vless-config-generator.conf"
    mode: '0644'
  become: yes
  notify: Reload nginx
  tags:
    - vless-config-generator
    - vless-config-generator-nginx
...
