---
infisical_project_id: "286db07f-4dba-4ca9-a515-f017d77b8bf1"
infisical_path: "/hosts/zelgray-work"

docker_network: "active"
docker_volumes_directory: "/opt/docker"

cf_zone_domain: "zelgray.work"
cf_api_token_clear_cache: "{{ infisical_secrets.secrets['cf-api-token-clear-cache'] }}"
cf_purge_cache: true
...
